# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_key', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='addmusic',
            name='description',
        ),
        migrations.AddField(
            model_name='playlistmusic',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AddMusic'),
        ),
    ]
